name: Upload CodeCov Report
on: [push, pull_request]
jobs:
  run:
    runs-on: windows-latest
    name: Build, Test , Upload Code Coverage Report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: ‘2’
        id: checkout_code
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild
      - name: Run MSBuild
        id: run_msbuild
        run: msbuild HelloCov.sln
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest
      - name: Setup OpenCppCoverage with XmlExporter and add to PATh
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          choco install OpenCppCoverage -y
          Invoke-WebRequest -OutFile XmlExporter-x64.zip https://github.com/berryzplus/XmlExporter/releases/download/v1.0.0/XmlExporter-x64.zip
          7z e XmlExporter-x64.zip
          Move-Item -Path XmlExporter.dll -Destination "C:\Program Files\OpenCppCoverage\Plugins\Exporter\xml.dll"
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
      - name: Generate Report
        id: generate_test_report
        shell: cmd
        run: OpenCppCoverage.exe --sources HelloCov --export_type xml:HelloCov.xml -- "vstest.console.exe" x64\Debug\HelloTest.dll
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./HelloCov.xml
          fail_ci_if_error: true